package interpreter_test

import (
	"testing"

	"github.com/texttheater/bach/errors"
	"github.com/texttheater/bach/interpreter"
	"github.com/texttheater/bach/states"
	"github.com/texttheater/bach/types"
)

func TestText(t *testing.T) {
	interpreter.TestProgram(
		`"abc"`,
		types.StrType{},
		states.StrValue("abc"),
		nil,
		t,
	)
	interpreter.TestProgram(
		`"\"\\abc\""`,
		types.StrType{},
		states.StrValue(`"\abc"`),
		nil,
		t,
	)
	interpreter.TestProgram(
		`1 "abc"`,
		types.StrType{},
		states.StrValue("abc"),
		nil,
		t,
	)
	interpreter.TestProgram(
		`"a{2 +2}"`,
		types.StrType{},
		states.StrValue("a4"),
		nil,
		t,
	)
	interpreter.TestProgram(
		`"{{}}"`,
		types.StrType{},
		states.StrValue("{}"),
		nil,
		t,
	)
	interpreter.TestProgram(
		`"{{}"`,
		nil,
		nil,
		errors.SyntaxError(
			errors.Code(errors.Syntax),
		),
		t,
	)
	interpreter.TestProgram(
		`"\t"`,
		types.StrType{},
		states.StrValue("\t"),
		nil,
		t,
	)
	interpreter.TestProgram(
		`"日本語"`,
		types.StrType{},
		states.StrValue("日本語"),
		nil,
		t,
	)
	interpreter.TestProgram(
		`"\u65e5\u672c\u8a9e"`,
		types.StrType{},
		states.StrValue("日本語"),
		nil,
		t,
	)
	interpreter.TestProgram(
		`"\U000065e5\U0000672c\U00008a9e"`,
		types.StrType{},
		states.StrValue("日本語"),
		nil,
		t,
	)
	interpreter.TestProgram(
		`"\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e"`,
		types.StrType{},
		states.StrValue("日本語"),
		nil,
		t,
	)
}
